>P1;chimera_3KQ7_A
structureX:chimera_3KQ7_A:   5:A:LAST:A:chimera_3KQ7_A::-1.00:-1.00
----MGSSH----HHHHHSS-GLVPRG------S-----HM----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----MGSSH----HHHHHSS-GLVPRG------S-----HM----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3NPC_A
structureX:chimera_3NPC_A:   7:A:LAST:A:chimera_3NPC_A::-1.00:-1.00
-------------------------------M-S------K----------------S--
----------K--V--DNQF-Y-S---VE-------------VA-D----ST-------F
--T-VLKRYQ-QL-KPIGSGAQGIVCAAFDT-V-L--G----I-----NVAVKKLSR-P-
FQNQT--H-----A--KRAYRELVLLKC-VN-HKN-IISLLNVFTP-QKTLEE---FQ-D
VYLVMELM--DANLCQVIH-------ME---------------------------LDHER
MSYLLYQMLCGIKHLHSA----GIIHRDLKPSNIVVKSD-C----T-LKILDFGLAR---
-T----AC-TN---------FM-M-TPYV--VTR---YYRAPEVILG------M-GYA-A
NVDIWSVGCIMGELVK-GCV-IF---QG--T-----D-HI----D---QWNK-V-IE---
QLGTPSAEFMAALQP-T-----------------VRNYVENRP-K-------Y------P
GIKFE--ELF--PDW--IFPSESERD--K-I-KTSQA-RDLLSKMLVIDPDKRIS-V---
---DEALR---HP-YITVWY-DP-AEAE------AP-PPQ------IY--D---------
A----------QLE--EREHA-IEE--WKE-LIYKEVMD-------WE------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
-------------------------------M-S------K----------------S--
----------K--V--DNQF-Y-S---VE-------------VA-D----ST-------F
--T-VLKRYQ-QL-KPIGSGAQGIVCAAFDT-V-L--G----I-----NVAVKKLSR-P-
FQNQT--H-----A--KRAYRELVLLKC-VN-HKN-IISLLNVFTP-QKTLEE---FQ-D
VYLVMELM--DANLCQVIH-------ME---------------------------LDHER
MSYLLYQMLCGIKHLHSA----GIIHRDLKPSNIVVKSD-C----T-LKILDFGLAR---
-T----AC-TN---------FM-M-TPYV--VTR---YYRAPEVILG------M-GYA-A
NVDIWSVGCIMGELVK-GCV-IF---QG--T-----D-HI----D---QWNK-V-IE---
QLGTPSAEFMAALQP-T-----------------VRNYVENRP-K-------Y------P
GIKFE--ELF--PDW--IFPSESERD--K-I-KTSQA-RDLLSKMLVIDPDKRIS-V---
---DEALR---HP-YITVWY-DP-AEAE------AP-PPQ------IY--D---------
A----------QLE--EREHA-IEE--WKE-LIYKEVMD-------WE------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_2BAJ_A
structureX:chimera_2BAJ_A:  -1:A:LAST:A:chimera_2BAJ_A::-1.00:-1.00
------------HHHHHHS-----------------------------------------
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------HHHHHHS-----------------------------------------
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_1UWH_A
structureX:chimera_1UWH_A: 447:A:LAST:A:chimera_1UWH_A::-1.00:-1.00
------------------------------------------------------------
-------------------------------------------------D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---A---P----Q
LAIVTQWCE-GSSLYHHLH-I--I---E-----------------T-------K-FEMIK
LIDIARQTAQGMDYLHAK----SIIHRDLKSNNIFLHED-----L-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DKN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIF--MVG---
--------------------RG--Y--LSP---D---------L---------S------
----------------K---------VR-SNC-PKA-MKRLMAECLKKKRDERPLF----
---PQILAS---IE-LLARSL--PK-----------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
-------------------------------------------------D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---A---P----Q
LAIVTQWCE-GSSLYHHLH-I--I---E-----------------T-------K-FEMIK
LIDIARQTAQGMDYLHAK----SIIHRDLKSNNIFLHED-----L-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DKN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIF--MVG---
--------------------RG--Y--LSP---D---------L---------S------
----------------K---------VR-SNC-PKA-MKRLMAECLKKKRDERPLF----
---PQILAS---IE-LLARSL--PK-----------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_2YIY_A
structureX:chimera_2YIY_A:  27:A:LAST:A:chimera_2YIY_A::-1.00:-1.00
------------------------------------------------------------
-----------------------------------------------------S--LH-M
-I-D-YKEIE-VE-EVVGRGAFGVVCKAK---W-R--A----K-----DVAIKQIE-S-E
-S---E---------RKAFIVELRQLSR-V-NHPN-IVKLYGAC--L---N---P-----
VCLVMEYAE-GGSLYNVLH-G--AE--PLP-----------------------Y-YTAAH
AMSWCLQCSQGVAYLHSM-QPKALIHRDLKPPNLLLVAG-G---T-VLKICDFGTA-CDI
QT-------------------H-M-TNNKG--SA---AWMAPEVFEG------S-NY-SE
KCDVFSWGIILWEVIT-RRK-PF-DEIG----------------GPAFRIM------WAV
------------------H-NGT-----RP---P-------------------L------
---------------I-------------KNL-PKP-IESLMTRCWSKDPSQRPSM----
---EEIVKI---MT-HLMRYF--PGADEPLQ--Y--P--C---QHS---L-P-PGEDGR-
-------VE---------------------------------------------------
----------------------------PYVDFAEFYRLWSVDHGE
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
-----------------------------------------------------S--LH-M
-I-D-YKEIE-VE-EVVGRGAFGVVCKAK---W-R--A----K-----DVAIKQIE-S-E
-S---E---------RKAFIVELRQLSR-V-NHPN-IVKLYGAC--L---N---P-----
VCLVMEYAE-GGSLYNVLH-G--AE--PLP-----------------------Y-YTAAH
AMSWCLQCSQGVAYLHSM-QPKALIHRDLKPPNLLLVAG-G---T-VLKICDFGTA-CDI
QT-------------------H-M-TNNKG--SA---AWMAPEVFEG------S-NY-SE
KCDVFSWGIILWEVIT-RRK-PF-DEIG----------------GPAFRIM------WAV
------------------H-NGT-----RP---P-------------------L------
---------------I-------------KNL-PKP-IESLMTRCWSKDPSQRPSM----
---EEIVKI---MT-HLMRYF--PGADEPLQ--Y--P--C---QHS---L-P-PGEDGR-
-------VE---------------------------------------------------
----------------------------PYVDFAEFYRLWSVDHGE
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3GCV_A
structureX:chimera_3GCV_A:   4:A:LAST:A:chimera_3GCV_A::-1.00:-1.00
----------------------------------------G----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------SQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-S----E-LKILDFGLCR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SLE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----------------------------------------G----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------SQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-S----E-LKILDFGLCR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SLE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3HV5_A
structureX:chimera_3HV5_A:   4:A:LAST:A:chimera_3HV5_A::-1.00:-1.00
----------------------------------------G----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----------------------------------------G----------------S--
----------Q--E--RPTF-Y-R---QE-------------LN-K----TI-------W
--E-VPERYQ-NL-SPVGSGAYGSVCAAFDT-K-T--G----L-----RVAVKKLSR-P-
FQSII--H-----A--KRTYRELRLLKH-MK-HEN-VIGLLDVFTP-ARSLEE---FN-D
VYLVTHLM--GADLNNIVK-------CQ----------------K----------LTDDH
VQFLIYQILRGLKYIHSA----DIIHRDLKPSNLAVNED-C----E-LKILDFGLAR---
-H----TD-D-----------E-M-TGYV--ATR---WYRAPEIMLN---W--M-HYN-Q
TVDIWSVGCIMAELLT-GRT-LF---PG--T-----D-HI----D---QLKL-I-LR---
LVGTPGAELLKKISSES-----------------ARNYIQSLT-Q-------M------P
KMNF---------AN--VFI----------G-ANPLA-VDLLEKMLVLDSDKRIT-A---
---AQALA---HA-YFAQYH-DP-DDEP------VA---D------PY--D---------
Q----------SFE--SRDLL-IDE--WKS-LTYDEVISFVP----P-PLDQEE------
----M-------------------E--S------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3II5_A
structureX:chimera_3II5_A: 447:A:LAST:A:chimera_3II5_A::-1.00:-1.00
MDRG----------------------------SH----------------------H-HH
HHSE---D--RN----RM-------------K-TLG--RRD-----SS-D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---K---P----Q
LAIVTQWCE-GSSLYHHLH-I--I---E-----------------T-------K-FEMIK
LIDIARQTAQGMDYLHAK----SIIHRDLKSNNIFLHED-----L-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DKN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIF--MVG---
--------------------RG--Y--LSP---D---------L---------S------
----------------K---------VR-SNC-PKA-MKRLMAECLKKKRDERPLF----
---PQILAS---IE-LLARSL--PKIH---R-----------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
MDRG----------------------------SH----------------------H-HH
HHSE---D--RN----RM-------------K-TLG--RRD-----SS-D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---K---P----Q
LAIVTQWCE-GSSLYHHLH-I--I---E-----------------T-------K-FEMIK
LIDIARQTAQGMDYLHAK----SIIHRDLKSNNIFLHED-----L-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DKN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIF--MVG---
--------------------RG--Y--LSP---D---------L---------S------
----------------K---------VR-SNC-PKA-MKRLMAECLKKKRDERPLF----
---PQILAS---IE-LLARSL--PKIH---R-----------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3QC4_A
structureX:chimera_3QC4_A:  76:A:LAST:A:chimera_3QC4_A::-1.00:-1.00
---------GPL--------GS-----MDGTA-AEPRPG---------------------
----------A--G--S--L---QHA-QP---------------PP--------QPRKK-
----RPEDFKF-G-KILGEGSFSTVVLAREL--AT--S----R-----EYAIKILEK-R-
HI-----IKEN-KV--PYVTRERDVMSR-LD-HPF-FVKLYFTFQD----------DE-K
LYFGLSYAKN-GELLKYIR-K--I---------------------G-------S-FDETC
TRFYTAEIVSALEYLHGK----GIIHRDLKPENILLNED-----MH-IQITDFGTAK-VL
SP----ESKQA-----------RA-NSFV--GTA---QYVSPELLTE------K-SAC-K
SSDLWALGCIIYQLVA-GLP-PFR---A-GN-------EY--------LIFQ----K--I
IKLEYD-----------------------------------FP-----------------
----------------------------A-A-FFPKA-RDLVEKLLVLDATKRLG-CEEM
EGYGPLKA---HP-FFESVT-WE-NLHQ---------Q---------------------T
PPK-LT------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
---------GPL--------GS-----MDGTA-AEPRPG---------------------
----------A--G--S--L---QHA-QP---------------PP--------QPRKK-
----RPEDFKF-G-KILGEGSFSTVVLAREL--AT--S----R-----EYAIKILEK-R-
HI-----IKEN-KV--PYVTRERDVMSR-LD-HPF-FVKLYFTFQD----------DE-K
LYFGLSYAKN-GELLKYIR-K--I---------------------G-------S-FDETC
TRFYTAEIVSALEYLHGK----GIIHRDLKPENILLNED-----MH-IQITDFGTAK-VL
SP----ESKQA-----------RA-NSFV--GTA---QYVSPELLTE------K-SAC-K
SSDLWALGCIIYQLVA-GLP-PFR---A-GN-------EY--------LIFQ----K--I
IKLEYD-----------------------------------FP-----------------
----------------------------A-A-FFPKA-RDLVEKLLVLDATKRLG-CEEM
EGYGPLKA---HP-FFESVT-WE-NLHQ---------Q---------------------T
PPK-LT------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_4EQU_A
structureX:chimera_4EQU_A:  24:A:LAST:A:chimera_4EQU_A::-1.00:-1.00
----------------------------------------S-------------------
----MRK--SR--E--YEH--------------------------V----RR----D-L-
--D-PNEVWEI-V-GELGDGAFGKVYKAKNK--ET--G----A-----LAAAKVIET-K-
S--E--------EE-LEDYIVEIEILAT-CD-HPY-IVKLLGAYYH----------DG-K
LWIMIEFCPG-GAVDAIML-E----L------------------DR-------G-LTEPQ
IQVVCRQMLEALNFLHSK----RIIHRDLKAGNVLMTLE-----GD-IRLADFGVSA-KN
-----LKT-----------LQK-R-DSFI--GTP---YWMAPEVVMCETMKD-T-PYD-Y
KADIWSLGITLIEMAQ-IEP-PHH---E--L-----N-PM----R---VLLK-I------
------------------------------AKS-D------PP-T----------LL---
TP--------------------------S-K-WSVEF-RDFLKIALDKNPETRPS-A---
---AQLLE---HP-FVSSIT-SN--KA--------------------------------L
-RELVAE--AKA--E-VM---E-E------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----------------------------------------S-------------------
----MRK--SR--E--YEH--------------------------V----RR----D-L-
--D-PNEVWEI-V-GELGDGAFGKVYKAKNK--ET--G----A-----LAAAKVIET-K-
S--E--------EE-LEDYIVEIEILAT-CD-HPY-IVKLLGAYYH----------DG-K
LWIMIEFCPG-GAVDAIML-E----L------------------DR-------G-LTEPQ
IQVVCRQMLEALNFLHSK----RIIHRDLKAGNVLMTLE-----GD-IRLADFGVSA-KN
-----LKT-----------LQK-R-DSFI--GTP---YWMAPEVVMCETMKD-T-PYD-Y
KADIWSLGITLIEMAQ-IEP-PHH---E--L-----N-PM----R---VLLK-I------
------------------------------AKS-D------PP-T----------LL---
TP--------------------------S-K-WSVEF-RDFLKIALDKNPETRPS-A---
---AQLLE---HP-FVSSIT-SN--KA--------------------------------L
-RELVAE--AKA--E-VM---E-E------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_4F7N_A
structureX:chimera_4F7N_A:   0:A:LAST:A:chimera_4F7N_A::-1.00:-1.00
----------------------------------------DKM-----DY-------DFK
--------------------V-K-------------------LS-S--E----------R
--ERVEDLFE-YEGCKVGRGTYGHVYKAKR-KD-GKDD----K-----DYALKQIE----
--GTG--I-----S--MSACREIALLRE-LK-HPN-VISLQKVFLS-----HA---DR-K
VWLLFDYA--EHDLWHIIK-FHR---------------------ASKANKKPVQ-LPRGM
VKSLLYQILDGIHYLHAN----WVLHRDLKPANILVMGEG-PERGR-VKIADMGFAR-LF
N-----S---PLK-----PLAD-L-DPVV--VTF---WYRAPELLLG---A--R-HYT-K
AIDIWAIGCIFAELLT-SEP-IFH---C--RQEDIKT-SNPYHHD---QLDR-I-FN---
VMGFPADKDWEDIKK--------------------------MP-E-HSTLMK--DFRRN-
--TYTNCSLIKYMEK--HKV----------K-PDSKA-FHLLQKLLTMDPIKRIT-S---
---EQAMQ---DP-YFLEDP-LP-TSDV------FA----GCQ-----------------
------------IPYPKREFL-TEEEPDDK---GDKKNQ-QQQQGN----N---H-----
----TNGTGHPGNQ-DSSHTQGPPLKK-------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----------------------------------------DKM-----DY-------DFK
--------------------V-K-------------------LS-S--E----------R
--ERVEDLFE-YEGCKVGRGTYGHVYKAKR-KD-GKDD----K-----DYALKQIE----
--GTG--I-----S--MSACREIALLRE-LK-HPN-VISLQKVFLS-----HA---DR-K
VWLLFDYA--EHDLWHIIK-FHR---------------------ASKANKKPVQ-LPRGM
VKSLLYQILDGIHYLHAN----WVLHRDLKPANILVMGEG-PERGR-VKIADMGFAR-LF
N-----S---PLK-----PLAD-L-DPVV--VTF---WYRAPELLLG---A--R-HYT-K
AIDIWAIGCIFAELLT-SEP-IFH---C--RQEDIKT-SNPYHHD---QLDR-I-FN---
VMGFPADKDWEDIKK--------------------------MP-E-HSTLMK--DFRRN-
--TYTNCSLIKYMEK--HKV----------K-PDSKA-FHLLQKLLTMDPIKRIT-S---
---EQAMQ---DP-YFLEDP-LP-TSDV------FA----GCQ-----------------
------------IPYPKREFL-TEEEPDDK---GDKKNQ-QQQQGN----N---H-----
----TNGTGHPGNQ-DSSHTQGPPLKK-------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_4JVG_A
structureX:chimera_4JVG_A: 448:A:LAST:A:chimera_4JVG_A::-1.00:-1.00
------------------------------------------------------------
---------------------------------GAM--DRD-----SS-D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---K---P----Q
LAIVTQWCE-GSSLYHHLH-A--S---E-----------------T-------K-FEMKK
LIDIARQTARGMDYLHAK----SIIHRDLKSNNIFLHED-----N-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DSN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIE--MVG---
--------------------RG--S--LSP---D---------L---------S------
----------------K---------VR-SNC-PKR-MKRLMAECLKKKRDERPSF----
---PRILAE---IE-ELAREL--SG-----------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
---------------------------------GAM--DRD-----SS-D-DW----E-I
-P---DGQIT-VG-QRIGSGSFGTVYKGK---W-H--G----------DVAVKMLN-VTA
-P----T----PQQ-LQAFKNEVGVLRK-T-RHVN-ILLFMGYS--T---K---P----Q
LAIVTQWCE-GSSLYHHLH-A--S---E-----------------T-------K-FEMKK
LIDIARQTARGMDYLHAK----SIIHRDLKSNNIFLHED-----N-TVKIGDFGLA-TVK
SRWSG--------------SHQ-F-EQLSGS--I---LWMAPEVIRMQ---DSN-PY-SF
QSDVYAFGIVLYELMT-GQL-PY-S--NI---N----N------R-DQ-IIE--MVG---
--------------------RG--S--LSP---D---------L---------S------
----------------K---------VR-SNC-PKR-MKRLMAECLKKKRDERPSF----
---PRILAE---IE-ELAREL--SG-----------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_4EYJ_A
structureX:chimera_4EYJ_A:   2:A:LAST:A:chimera_4EYJ_A::-1.00:-1.00
----MGSS----HHHHHHSS-GLVPRG------S------M----------S-----L--
----------I--R--KKGF-Y-K---QD-------------VN-K----TA-------W
--E-LPKTYV-SP-THVGSGAYGSVCSAIDK-R-S--G----E-----KVAIKKLSR-P-
FQSEI--F-----A--KRAYRELLLLKH-MQ-HEN-VIGLLDVFTP-ASSLRN---FY-D
FYLVMPFM--QTDLQKIMG-------ME---------------------------FSEEK
IQYLVYQMLKGLKYIHSA----GVVHRDLKPGNLAVNED-C----E-LKILDFGLAR---
-H----AD-A-----------E-M-TGYV--VTR---WYRAPEVILS---W--M-HYN-Q
TVDIWSVGCIMAEMLT-GKT-LF---KG--K-----D-YL----D---QLTQ-I-LK---
VTGVPGTEFVQKLNDKA-----------------AKSYIQSLP-Q-------T------P
RKDF---------TQ--LFP----------R-ASPQA-ADLLEKMLELDVDKRLT-A---
---AQALT---HP-FFEPFR-DP-EEET------EA--QQ------PF--D---------
D----------SLE--HEKLT-VDE--WKQ-HIYKEIVNFSP----I-------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
----MGSS----HHHHHHSS-GLVPRG------S------M----------S-----L--
----------I--R--KKGF-Y-K---QD-------------VN-K----TA-------W
--E-LPKTYV-SP-THVGSGAYGSVCSAIDK-R-S--G----E-----KVAIKKLSR-P-
FQSEI--F-----A--KRAYRELLLLKH-MQ-HEN-VIGLLDVFTP-ASSLRN---FY-D
FYLVMPFM--QTDLQKIMG-------ME---------------------------FSEEK
IQYLVYQMLKGLKYIHSA----GVVHRDLKPGNLAVNED-C----E-LKILDFGLAR---
-H----AD-A-----------E-M-TGYV--VTR---WYRAPEVILS---W--M-HYN-Q
TVDIWSVGCIMAEMLT-GKT-LF---KG--K-----D-YL----D---QLTQ-I-LK---
VTGVPGTEFVQKLNDKA-----------------AKSYIQSLP-Q-------T------P
RKDF---------TQ--LFP----------R-ASPQA-ADLLEKMLELDVDKRLT-A---
---AQALT---HP-FFEPFR-DP-EEET------EA--QQ------PF--D---------
D----------SLE--HEKLT-VDE--WKQ-HIYKEIVNFSP----I-------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3L8V_A
structureX:chimera_3L8V_A:1054:A:LAST:A:chimera_3L8V_A::-1.00:-1.00
-------------------------------------------GANTVHIDLSALN----
--------P---EL-V----------Q---A-V-QH--VV---------I-GP----S--
-----SLIVH-FN-EVIGRGHFGCVYHGT---L-L--D--ND-GKK-IHCAVKSLN--RI
------T---D-IGEVSQFLTEGIIMKDF--SHP-NVLSLLGIC--L-----RS---EGS
PLVVLPYMK-HGDLRNFI-RN--E---TH-N------------------------PTVKD
LIGFGLQVAKGMKFLAS----KKFVHRDLAARNCMLDEK-F-----TVKVADFGLA-RDM
Y---------D--KEFDS------VHNKTG--AKLPVKWMALESLQ------TQK-F-TT
KSDVWSFGVLLWELMTRGA-PPY-P--DV---N------T----F-D--ITV-Y-----L
-----------------L-Q---GR-R-LL---------------Q-------P------
-----------------------------EY-CPDP-LYEVMLKCWHPKAEMRPSF----
---SELVS-RISAI-FST-------------FI---------------------------
------------------------------G------------------------EHYVH
--VN---------A-TYV-NVK------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
-------------------------------------------GANTVHIDLSALN----
--------P---EL-V----------Q---A-V-QH--VV---------I-GP----S--
-----SLIVH-FN-EVIGRGHFGCVYHGT---L-L--D--ND-GKK-IHCAVKSLN--RI
------T---D-IGEVSQFLTEGIIMKDF--SHP-NVLSLLGIC--L-----RS---EGS
PLVVLPYMK-HGDLRNFI-RN--E---TH-N------------------------PTVKD
LIGFGLQVAKGMKFLAS----KKFVHRDLAARNCMLDEK-F-----TVKVADFGLA-RDM
Y---------D--KEFDS------VHNKTG--AKLPVKWMALESLQ------TQK-F-TT
KSDVWSFGVLLWELMTRGA-PPY-P--DV---N------T----F-D--ITV-Y-----L
-----------------L-Q---GR-R-LL---------------Q-------P------
-----------------------------EY-CPDP-LYEVMLKCWHPKAEMRPSF----
---SELVS-RISAI-FST-------------FI---------------------------
------------------------------G------------------------EHYVH
--VN---------A-TYV-NVK------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_4H1J_A
structureX:chimera_4H1J_A: 419:A:LAST:A:chimera_4H1J_A::-1.00:-1.00
------------------------------------------------------------
----------------M---------H--HH----HHHSSGLV-PRGS-P-QY----G--
IA---REDVV-LN-RILGEGFFGEVYEGV---Y-T--NH--K-GEKI-NVAVKTCKKDCT
------L---D-N--KEKFMSEAVIMKNL--DHP-HIVKLIGII--E-----E--E---P
TWIIMELYP-YGELGHYL-ER--N---KN-S------------------------LKVLT
LVLYSLQICKAMAYLES----INCVHRDIAVRNILVASP-E-----CVKLGDFGLS-RYI
E---------D--E--DY------YK-ASV--TRLPIKWMSPESIN------FRR-F-TT
ASDVWMFAVCMWEILSFGK-QPF-F--WL---E------N----K-D--VIG-V-----L
-----------------E-K---GD-R-LP---------------K-------P------
-----------------------------DL-CPPV-LYTLMTRCWDYDPSDRPRF----
---TELVC-SLSDV-YQM-------------EK------------D--IA-ME-------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
----------------M---------H--HH----HHHSSGLV-PRGS-P-QY----G--
IA---REDVV-LN-RILGEGFFGEVYEGV---Y-T--NH--K-GEKI-NVAVKTCKKDCT
------L---D-N--KEKFMSEAVIMKNL--DHP-HIVKLIGII--E-----E--E---P
TWIIMELYP-YGELGHYL-ER--N---KN-S------------------------LKVLT
LVLYSLQICKAMAYLES----INCVHRDIAVRNILVASP-E-----CVKLGDFGLS-RYI
E---------D--E--DY------YK-ASV--TRLPIKWMSPESIN------FRR-F-TT
ASDVWMFAVCMWEILSFGK-QPF-F--WL---E------N----K-D--VIG-V-----L
-----------------E-K---GD-R-LP---------------K-------P------
-----------------------------DL-CPPV-LYTLMTRCWDYDPSDRPRF----
---TELVC-SLSDV-YQM-------------EK------------D--IA-ME-------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_3EWH_A
structureX:chimera_3EWH_A: 815:A:LAST:A:chimera_3EWH_A::-1.00:-1.00
------------------------------------------------------------
--------------------------E---H-A-E-R-LP----YDA--S-KW----E--
FP---RDRLK-LG-KPLGRGAFGQVIEAD---A-F--GIDKT-ATC-RTVAVKMLK-EGA
------T---H-SE-HRALMSELKILIHI-GHHL-NVVNLLGAC--T-----KP-G-G-P
LMVITEFCK-FGNLSTYL-RS--K---RN-EFVPYKVAPEDLYK-------D--FLTLEH
LICYSFQVAKGMEFLAS----RKCIHRDLAARNILLSEK-N-----VVKICDFGLA-RDI
Y---------K--D--PD------YVRKGD--ARLPLKWMAPETIF------DRV-Y-TI
QSDVWSFGVLLWEIFSLGA-SPY-P--GV---K------I----D-E--EFCRR-----L
-----------------K-E---GT-R-MR---------------A-------P------
-----------------------------DY-TTPE-MYQTMLDCWHGEPSQRPTF----
---SELVE-HLGNL-LQA-------------NA---------------------------
------------------------------Q------------------------QDR--
HHHH---------HH-------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
--------------------------E---H-A-E-R-LP----YDA--S-KW----E--
FP---RDRLK-LG-KPLGRGAFGQVIEAD---A-F--GIDKT-ATC-RTVAVKMLK-EGA
------T---H-SE-HRALMSELKILIHI-GHHL-NVVNLLGAC--T-----KP-G-G-P
LMVITEFCK-FGNLSTYL-RS--K---RN-EFVPYKVAPEDLYK-------D--FLTLEH
LICYSFQVAKGMEFLAS----RKCIHRDLAARNILLSEK-N-----VVKICDFGLA-RDI
Y---------K--D--PD------YVRKGD--ARLPLKWMAPETIF------DRV-Y-TI
QSDVWSFGVLLWEIFSLGA-SPY-P--GV---K------I----D-E--EFCRR-----L
-----------------K-E---GT-R-MR---------------A-------P------
-----------------------------DY-TTPE-MYQTMLDCWHGEPSQRPTF----
---SELVE-HLGNL-LQA-------------NA---------------------------
------------------------------Q------------------------QDR--
HHHH---------HH-------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_2OG8_A
structureX:chimera_2OG8_A: 237:A:LAST:A:chimera_2OG8_A::-1.00:-1.00
------------------------------------------------------------
-------------------------------------------------D-EW----E--
VP---RETLK-LV-ERLGAGQFGEVWMGY---Y-N--GH--------TKVAVKSLK-QGS
------M---S-P---DAFLAEANLMKQL--QHQ-RLVRLYAVV--T-----Q--E---P
IYIITEYME-NGSLVDFL-KT--P---SG-I-----------------------KLTINK
LLDMAAQIAEGMAFIEE----RNYIHRDLRAANILVSDT-L-----SCKIADFGLA-RLI
----------E--D--NE------YTAREG--AKFPIKWTAPEAIN------YGT-F-TI
KSDVWSFGILLTEIVTHGR-IPY-P--GM---T------N----P-E--VIQ-N-----L
-----------------E-R---GY-R-MV---------------R-------P------
-----------------------------DN-CPEE-LYQLMRLCWKERPEDRPTF----
---DYLRS-VLEDF-FTA------------------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
-------------------------------------------------D-EW----E--
VP---RETLK-LV-ERLGAGQFGEVWMGY---Y-N--GH--------TKVAVKSLK-QGS
------M---S-P---DAFLAEANLMKQL--QHQ-RLVRLYAVV--T-----Q--E---P
IYIITEYME-NGSLVDFL-KT--P---SG-I-----------------------KLTINK
LLDMAAQIAEGMAFIEE----RNYIHRDLRAANILVSDT-L-----SCKIADFGLA-RLI
----------E--D--NE------YTAREG--AKFPIKWTAPEAIN------YGT-F-TI
KSDVWSFGILLTEIVTHGR-IPY-P--GM---T------N----P-E--VIQ-N-----L
-----------------E-R---GY-R-MV---------------R-------P------
-----------------------------DN-CPEE-LYQLMRLCWKERPEDRPTF----
---DYLRS-VLEDF-FTA------------------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;chimera_2PL0_A
structureX:chimera_2PL0_A: 231:A:LAST:A:chimera_2PL0_A::-1.00:-1.00
------------------------------------------------------------
------------GSHMQ---------T---Q-K-PQ--KP--W-WE---D-EW----E--
VP---RETLK-LV-ERLGAGQFGEVWMGY---Y-N--GH--------TKVAVKSLK-QGS
------M---S-P---DAFLAEANLMKQL--QHQ-RLVRLYAVV--T-----Q--E---P
IYIITEYME-NGSLVDFL-KT--P---SG-I-----------------------KLTINK
LLDMAAQIAEGMAFIEE----RNYIHRDLRAANILVSDT-L-----SCKIADFGLA-RLI
----------E--D--NE------YTAREG--AKFPIKWTAPEAIN------YGT-F-TI
KSDVWSFGILLTEIVTHGR-IPY-P--GM---T------N----P-E--VIQ-N-----L
-----------------E-R---GY-R-MV---------------R-------P------
-----------------------------DN-CPEE-LYQLMRLCWKERPEDRPTF----
---DYLRS-VLEDF-FTA-------------TE---------------------------
------------------------------G------------------------QYQPQ
--P-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------GSHMQ---------T---Q-K-PQ--KP--W-WE---D-EW----E--
VP---RETLK-LV-ERLGAGQFGEVWMGY---Y-N--GH--------TKVAVKSLK-QGS
------M---S-P---DAFLAEANLMKQL--QHQ-RLVRLYAVV--T-----Q--E---P
IYIITEYME-NGSLVDFL-KT--P---SG-I-----------------------KLTINK
LLDMAAQIAEGMAFIEE----RNYIHRDLRAANILVSDT-L-----SCKIADFGLA-RLI
----------E--D--NE------YTAREG--AKFPIKWTAPEAIN------YGT-F-TI
KSDVWSFGILLTEIVTHGR-IPY-P--GM---T------N----P-E--VIQ-N-----L
-----------------E-R---GY-R-MV---------------R-------P------
-----------------------------DN-CPEE-LYQLMRLCWKERPEDRPTF----
---DYLRS-VLEDF-FTA-------------TE---------------------------
------------------------------G------------------------QYQPQ
--P-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GGELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HIKITDFGLC-KEG
I---------K--D--G----ATM-KTFCG--TP---EYLAPEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F---------------------------------F----------
------------------------------------------------------------
----------------------------------------------
*

>P1;cido.AKT1
sequence:cido.AKT1:1   :A:LAST:A:cido.AKT1:::
------------------------------------------------------------
------------------------------------------------------------
--------FE-YL-KLLGKGTFGKVILVKE-KA-T--G----R-----YYAMKILK-KEV
-I-----VAKD-EV--AHTLTENRVLQN-S-RHPF-LTALKYSF--Q-----T--H-D-R
LCFVMEYAN-GG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ELFFHLS-R--E---------------------R-------V-FSEDR
ARFYGAEIVSALDYLHSEK---NVVYRDLKLENLMLDKD-----G-HI------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------KITDFGLC-/--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------PEVLED------N-DY-GR
AVDWWGLGVVMYEMMC-GRL-PF-Y--N----Q----D------H-E-KLFE--L----I
------------------L-M--EEI-RFP------R-----------------------
------------------------------TL-GPE-AKSLLSGLLKKDPKQRLGG-GS-
EDAKEIMQ-H--R--F--------------------------------------------
------------------------------------------------------------
----------------------------------------------
*

